In [ ]:
# Intermediate Exercises





# Let's install Tensorflow 2.0:

# Import the relevant libraries

import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

data = pd.read_csv("/content/california_housing_test.csv")

print(data.shape)
print(type(data))
print(data.head(3))


# Exercise number 2

# import relevant data
from scipy import sparse


eye = np.eye(40)
print(eye.shape); print(type(eye))# details of our data... 
print("Numpy array: \n", eye)
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n", sparse_matrix)



print(np.mean(data))
print(np.std(data)); 
print()

(3000, 9)
<class 'pandas.core.frame.DataFrame'>
   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
(40, 40)
<class 'numpy.ndarray'>
Numpy array: 
 [[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

SciPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 8)	1.0
  (9, 9)	1.0
  (10, 10)	1.0
  (11, 11)	1.0
  (12, 1

In [40]:
# Do 3 linear regressions, 3 logistic regressions and 3 maximum likelihoods. 

# Relevant libraries imported: 

import numpy as np; import array as array
from sklearn.linear_model import LinearRegression

# Data Set

x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])


# Shape of the data

print(x.shape); print(y.shape)

# Create our model 


model_one = LinearRegression()


# Fit the data to our data. 

model = LinearRegression().fit(x,y)


# Results

final_result_y = model.predict(x)
print(final_result_y)
print(f"predicted response: /n{final_result_y}")
find_coef = model.intercept_ + np.sum(model.coef_*x, axis = 1)
print(f"predicted response: /n{final_result_y}")


# We can also do polynomial regression. 

# Libraries

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Data 

# Needs to be a 2-d array for polynomial regression. 

x = np.array([1,2,34,2,1,45]).reshape(-1,1)
y = np.array([13,23,45,32,15,100])



transformation = PolynomialFeatures(degree =2, include_bias = False).fit_transform(x)
our_Model = LinearRegression().fit(transformation, y)
# Before we can apply the transformer we need to fit it. 


predicted_value = our_Model.predict(transformation); print(predicted_value)

print(f"The predicted response :\n {predicted_value}")
print(f" The coefficient of the determinant is: \n{predicted_value}")


(6, 1)
(6,)
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
predicted response: /n[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
predicted response: /n[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
[21.59834481 19.48197917 46.8995862  19.48197917 21.59834481 98.93976584]
The predicted response :
 [21.59834481 19.48197917 46.8995862  19.48197917 21.59834481 98.93976584]
 The coefficient of the determinant is: 
[21.59834481 19.48197917 46.8995862  19.48197917 21.59834481 98.93976584]


NameError: ignored